version: '3.8'

services:
  app:
    build: .
    container_name: node-ts-starter-app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - maildev
    volumes:
        - .:/usr/src/app

  mongo:
    image: mongo
    container_name: node-ts-starter-mongo
    ports:
      - "${MONGO_CLIENT_PORT}:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: node-ts-starter-redis
    ports:
      - "${REDIS_SERVER_PORT}:6379"

  maildev:
    image: maildev/maildev
    container_name: node-ts-starter-maildev
    ports:
      - "${MAILDEV_SMTP}:1025"
      - "${MAILDEV_WEBAPP_PORT}:1080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1080"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo-data:
  minio-data:
